import{beforeEach,describe,expect,it}from"vitest";
import{mkdtempSync,rmSync}from"node:fs";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{spawnSync}from"node:child_process";
import{fileURLToPath}from"node:url";
import{ackHandoff,authenticateDevice,authenticateGrant,completePairing,createHandoff,latestHandoff,resetStore,revokeConnectionGrant,revokeDeviceToken,startPairing}from"../src/store.js";
describe("페어링과 handoff",()=>{
 beforeEach(resetStore);
 it("서버 생성 기기·토큰·일회용 코드·opaque grant",()=>{const pairing=startPairing();expect(authenticateDevice(pairing.deviceToken)).toBe(pairing.deviceId);const completed=completePairing(pairing.code);expect(completed?.connectionGrant).toBeTruthy();expect(authenticateGrant(completed!.connectionGrant)).toBe(pairing.deviceId);expect(completePairing(pairing.code)).toBeNull()});
 it("idempotency와 ACK",()=>{const first=createHandoff("d",{items:[1]},"same-key");const retry=createHandoff("d",{items:[1]},"same-key");expect(first.id).toBe(retry.id);expect(latestHandoff("d")?.id).toBe(first.id);expect(ackHandoff("d",first.id)).toBe(true);expect(latestHandoff("d")).toBeNull()});
 it("한 클라이언트의 코드 대입이 다른 클라이언트를 막지 않는다",()=>{const pairing=startPairing();for(let attempt=0;attempt<30;attempt+=1)expect(completePairing(String(100000+attempt),"client-a")).toBeNull();expect(completePairing(pairing.code,"client-a")).toBeNull();expect(completePairing(pairing.code,"client-b")?.connectionGrant).toBeTruthy()});
 it("코드별 제한이 다른 유효 코드를 막지 않는다",()=>{const pairing=startPairing();for(let attempt=0;attempt<5;attempt+=1)expect(completePairing("000000",`client-${attempt}`)).toBeNull();expect(completePairing(pairing.code,"fresh-client")?.connectionGrant).toBeTruthy()});
 it("기기 토큰 폐기 시 연결 grant와 handoff도 함께 폐기한다",()=>{const pairing=startPairing();const completed=completePairing(pairing.code,"client")!;createHandoff(pairing.deviceId,{items:[1]},"revoke-test");expect(revokeDeviceToken(pairing.deviceToken)).toBe(true);expect(authenticateDevice(pairing.deviceToken)).toBeNull();expect(authenticateGrant(completed.connectionGrant)).toBeNull();expect(latestHandoff(pairing.deviceId)).toBeNull()});
 it("연결 grant 폐기 시 기기 토큰도 함께 폐기한다",()=>{const pairing=startPairing();const completed=completePairing(pairing.code,"client")!;expect(revokeConnectionGrant(completed.connectionGrant)).toBe(true);expect(authenticateGrant(completed.connectionGrant)).toBeNull();expect(authenticateDevice(pairing.deviceToken)).toBeNull();expect(revokeConnectionGrant(completed.connectionGrant)).toBe(false)});
 it("서버 재시작 뒤에도 해시 토큰과 미수신 handoff를 복구한다",()=>{const directory=mkdtempSync(join(tmpdir(),"ddakdama-store-"));const stateFile=join(directory,"state.json");const cwd=fileURLToPath(new URL("..",import.meta.url));const run=(code:string,extra:Record<string,string>={})=>{const result=spawnSync(process.execPath,["--import","tsx","--input-type=module","-e",code],{cwd,encoding:"utf8",env:{...process.env,DDAKDAMA_STORE_FILE:stateFile,...extra}});expect(result.status,result.stderr).toBe(0);return JSON.parse(result.stdout.trim()) as Record<string,unknown>};try{const created=run(`const s=await import('./src/store.ts');const p=s.startPairing();const g=s.completePairing(p.code,'persist-client');const d=s.authenticateDevice(p.deviceToken);const h=s.createHandoff(d,{items:[1]},'persist-key');console.log(JSON.stringify({deviceToken:p.deviceToken,connectionGrant:g.connectionGrant,deviceId:d,handoffId:h.id}))`);const restored=run(`const s=await import('./src/store.ts');console.log(JSON.stringify({deviceId:s.authenticateDevice(process.env.DEVICE_TOKEN),grantDeviceId:s.authenticateGrant(process.env.CONNECTION_GRANT),handoffId:s.latestHandoff(process.env.DEVICE_ID)?.id}))`,{DEVICE_TOKEN:String(created.deviceToken),CONNECTION_GRANT:String(created.connectionGrant),DEVICE_ID:String(created.deviceId)});expect(restored).toEqual({deviceId:created.deviceId,grantDeviceId:created.deviceId,handoffId:created.handoffId})}finally{rmSync(directory,{recursive:true,force:true})}});
});
