import{test,expect}from"@playwright/test";

for(const route of["/dev/list","/dev/candidates","/dev/preflight","/dev/preflight-partial","/dev/result-success","/dev/result-partial-failure"]){
 test(`${route} 실제 Side Panel 컴포넌트 렌더링`,async({page})=>{await page.goto(route);await expect(page.locator("main.app-shell")).toBeVisible();for(const hiddenDeveloperLabel of["MCP URL","Server Origin","Extension Token","API Endpoint"])await expect(page.getByText(hiddenDeveloperLabel,{exact:false})).toHaveCount(0);await expect(page.locator("main.app-shell")).toHaveScreenshot(`${route.split("/").at(-1)}.png`,{animations:"disabled"})});
}

test("후보를 바꾸면 예상 합계가 갱신된다",async({page})=>{await page.goto("/dev/candidates");const total=page.getByTestId("estimated-total");const before=await total.textContent();await page.getByTestId("product-0").locator("button.product-row-main").click();const candidates=page.getByTestId("product-0").locator("button.candidate-row:enabled");await expect(candidates).toHaveCount(2);await candidates.nth(1).click();await expect(total).not.toHaveText(before??"")});

test("상품 확인 중 품목을 빼고 다시 포함하면 대상 수와 합계가 즉시 바뀐다",async({page})=>{await page.goto("/dev/candidates");const total=page.getByTestId("estimated-total");await expect(total).toHaveText("74,540원");await page.getByRole("button",{name:/닥터지.*이 품목 빼기/}).click();await expect(page.getByText("제외 1종",{exact:true})).toBeVisible();await expect(page.getByText("4/4종 선택",{exact:true})).toBeVisible();await expect(total).toHaveText("58,340원");await page.getByTestId("product-0").getByRole("button",{name:"다시 포함"}).click();await expect(page.getByText("제외 1종",{exact:true})).toHaveCount(0);await expect(page.getByText("5/5종 선택",{exact:true})).toBeVisible();await expect(total).toHaveText("74,540원")});

test("상품 확인 중 실물 수량을 바꾸면 담을 수량과 합계가 즉시 바뀐다",async({page})=>{await page.goto("/dev/candidates");const product=page.getByTestId("product-0");await product.locator("button.product-row-main").click();await product.getByRole("button",{name:/수량 1개 늘리기/}).click();await expect(product.getByText("실물 2개",{exact:false})).toBeVisible();await expect(page.getByTestId("estimated-total")).toHaveText("90,740원")});

test("저장된 결과에 비정상적인 거대 금액이 있어도 사용자 화면에 표시하지 않는다",async({page})=>{await page.goto("/dev/result-corrupt-price");const summary=page.getByLabel("담은 상품 가격 합계");await expect(summary.getByText("확인 불가",{exact:true})).toBeVisible();await expect(page.getByText("1,501,502,320",{exact:false})).toHaveCount(0);await expect(page.getByTestId("estimated-total")).toHaveText("74,540원")});

test("부분 실패는 전체 성공으로 표시하지 않는다",async({page})=>{await page.goto("/dev/result-partial-failure");await expect(page.getByText("성공 4종 · 실패 1종입니다. 실패 상품을 확인해 주세요.")).toBeVisible();await expect(page.getByText("모두 검증해 담았습니다.")).toHaveCount(0);await expect(page.getByRole("button",{name:"상품 페이지"})).toBeVisible();await expect(page.getByRole("button",{name:"다시 시도",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"실패 1종 다시 시도"})).toBeVisible()});

test("GPT 앱 연결과 재연결은 새 6자리 코드를 보여준다",async({page})=>{await page.goto("/dev/list");const connect=page.getByRole("button",{name:"6자리 코드 만들기"});await expect(connect).toHaveCount(1);await connect.click();await expect(page.getByLabel("연결 코드 482731")).toHaveText("482 731");await expect(page.getByRole("button",{name:"목록 받기"})).toBeVisible();await page.getByRole("button",{name:"새 코드"}).click();await expect(page.getByLabel("연결 코드 927364")).toHaveText("927 364");await expect(page.locator("main.app-shell")).toHaveScreenshot("gpt-connection-code.png",{animations:"disabled"})});

test("첫 화면은 비어 있고 예시는 사용자가 요청할 때만 채운다",async({page})=>{await page.goto("/dev/list");await expect(page.getByRole("heading",{name:"쇼핑 목록을 준비해 주세요"})).toBeVisible();await expect(page.getByLabel("직접 붙여넣기")).toHaveValue("");await expect(page.getByRole("button",{name:"목록을 입력해 주세요"})).toBeDisabled();await page.getByRole("button",{name:"예시 불러오기"}).click();await expect(page.getByLabel("직접 붙여넣기")).toHaveValue(/닥터지 레드 블레미쉬/);await expect(page.getByRole("button",{name:"실제 상품 찾기"})).toBeEnabled()});

test("직접 붙여넣은 목록은 하단 CTA에서 인식할 수 있다",async({page})=>{await page.goto("/dev/list");await page.getByLabel("직접 붙여넣기").fill("생수 2L 6개");const recognize=page.getByRole("button",{name:"목록 인식하기"});await expect(recognize).toBeEnabled();await recognize.click();await expect(page.getByRole("heading",{name:"상품 1종 · 실물 6개"})).toBeVisible();await expect(page.getByRole("button",{name:"실제 상품 찾기"})).toBeEnabled()});

test("360px 연결 코드 상태는 가로 스크롤 없이 표시된다",async({page})=>{await page.setViewportSize({width:360,height:800});await page.goto("/dev/list");await page.getByRole("button",{name:"6자리 코드 만들기"}).click();await expect(page.getByLabel("연결 코드 482731")).toHaveText("482 731");const metrics=await page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));expect(metrics.scrollWidth).toBeLessThanOrEqual(metrics.clientWidth)});

test("불일치 후보를 직접 선택하면 초과 수량을 알리고 preflight에 안전한 기대값을 보낸다",async({page})=>{await page.goto("/dev/list");await page.getByLabel("직접 붙여넣기").fill("테스트 주스 500ml 3개");await page.getByRole("button",{name:"목록 인식하기"}).click();await page.evaluate(()=>{(globalThis as typeof globalThis&{__lastPreflightJobs?:unknown}).__lastPreflightJobs=undefined;chrome.runtime.sendMessage=(async(message:unknown)=>{const request=message as{type:string;items?:Array<{id:string}>;jobs?:unknown[]};if(request.type==="DDAKDAMA_SEARCH_ALL"){const id=request.items?.[0]?.id??"line";return{ok:true,output:[{requestLineId:id,results:[{id:"manual",productId:"manual-product",vendorItemId:"manual-vendor",itemId:null,title:"테스트 주스 1L 2개 묶음",currentPrice:8000,unitsPerPackage:2,productUrl:"https://www.coupang.com/vp/products/manual",imageUrl:null,rocketDelivery:false,rating:4.5,reviewCount:20,advertised:false,source:"BROWSER"}]}]}}if(request.type==="DDAKDAMA_PREFLIGHT"){(globalThis as typeof globalThis&{__lastPreflightJobs?:unknown}).__lastPreflightJobs=request.jobs;return{results:(request.jobs??[]).map((job)=>({id:(job as{id:string}).id,status:"READY",verifiedPrice:8000}))}}return{ok:true}})as typeof chrome.runtime.sendMessage});await page.getByRole("button",{name:"실제 상품 찾기"}).click();const product=page.getByTestId("product-0");await expect(product.getByText("후보 1개 보기",{exact:true})).toBeVisible();await expect(product.locator("button.candidate-row")).toHaveCount(1);await product.locator("button.candidate-row").click();await expect(product.getByText("직접 선택",{exact:true}).first()).toBeVisible();await expect(product.getByText("실물 4개 (1개 초과)",{exact:false})).toBeVisible();await page.getByRole("button",{name:"1종 상세 확인하기"}).click();await expect(page.getByRole("heading",{name:"담기 전 확인"})).toBeVisible();const job=await page.evaluate(()=>(globalThis as typeof globalThis&{__lastPreflightJobs?:Array<Record<string,unknown>>}).__lastPreflightJobs?.[0]);expect(job).toMatchObject({cartPurchaseQuantity:2,expectedProductName:"테스트 주스 1L 2개 묶음",expectedBrand:null,expectedUnitSize:null,expectedStrength:null,expectedPackageContent:null})});

test("후보가 없으면 행 안에서 검색어를 바꿔 전체 후보를 다시 찾는다",async({page})=>{await page.goto("/dev/list");await page.getByLabel("직접 붙여넣기").fill("무향 세제 3개");await page.getByRole("button",{name:"목록 인식하기"}).click();await page.evaluate(()=>{let searches=0;chrome.runtime.sendMessage=(async(message:unknown)=>{const request=message as{type:string;items?:Array<{id:string}>};if(request.type!=="DDAKDAMA_SEARCH_ALL")return{ok:true};searches+=1;const id=request.items?.[0]?.id??"line";if(searches===1)return{ok:true,output:[{requestLineId:id,results:[],error:"NO_RESULTS"}]};return{ok:true,output:[{requestLineId:id,results:Array.from({length:5},(_,index)=>({id:`retry-${index}`,productId:`p-${index}`,vendorItemId:`v-${index}`,itemId:null,title:`무향 세제 리필 ${index+1}L`,currentPrice:5000+index*500,unitsPerPackage:2,productUrl:`https://www.coupang.com/vp/products/${index}`,imageUrl:null,rocketDelivery:false,rating:4.2,reviewCount:10,advertised:false,source:"BROWSER"}))}]}})as typeof chrome.runtime.sendMessage});await page.getByRole("button",{name:"실제 상품 찾기"}).click();const product=page.getByTestId("product-0");await expect(product.getByText("규격 미입력",{exact:false})).toBeVisible();const query=product.getByLabel("검색어 수정");await query.fill("무향 세제 리필");await product.getByRole("button",{name:"다시 검색"}).click();await expect(product.locator("button.candidate-row")).toHaveCount(5)});

test("사전검사 실패는 금액·실물수량과 함께 명시적 부분 담기를 제공한다",async({page})=>{await page.goto("/dev/preflight-partial");await expect(page.getByText("사전검사 통과 4종 · 확인 필요 1종입니다.")).toBeVisible();await expect(page.getByRole("button",{name:"확인된 4종 · 실물 6개 담기"})).toBeEnabled();await expect(page.getByText("48,090원",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"문제 상품 확인"})).toBeVisible();await expect(page.getByRole("button",{name:"다시 확인"})).toBeEnabled();await expect(page.getByRole("button",{name:"5종 장바구니에 담기"})).toHaveCount(0)});

test("묶음 상품 결과는 장바구니 행이 아닌 실물 수량으로 설명한다",async({page})=>{await page.goto("/dev/result-success");await expect(page.getByText("2개 묶음 1세트 담음 · 실물 2개",{exact:false})).toHaveCount(2);await expect(page.getByText("수량 0 → 1",{exact:false})).toHaveCount(0)});

test("완료 화면은 가격 합계와 쿠팡 장바구니 이동, 새 목록 시작을 각각 제공한다",async({page})=>{await page.goto("/dev/result-success");await expect(page.getByLabel("담은 상품 가격 합계").getByText("74,540원",{exact:true})).toHaveCount(2);const footer=page.locator("footer");const openCart=footer.getByRole("button",{name:"쿠팡 장바구니 보기"});const restart=footer.getByRole("button",{name:"새 목록 담기"});await expect(openCart).toBeVisible();await expect(restart).toBeVisible();await openCart.click();await expect(page.locator("html")).toHaveAttribute("data-demo-cart-opened","true");await restart.click();await expect(page.getByRole("heading",{name:"쇼핑 목록을 준비해 주세요"})).toBeVisible();await expect(page.getByLabel("직접 붙여넣기")).toHaveValue("")});
test("한 세션에서 목록 인식부터 후보 선택, 사전검사, 담기, 장바구니 이동과 새 목록까지 이어진다",async({page})=>{await page.goto("/dev/list?theme=light");await page.getByRole("button",{name:"예시 불러오기"}).click();await page.getByRole("button",{name:"실제 상품 찾기"}).click();await expect(page.getByTestId("estimated-total")).toHaveText("74,540원");const first=page.getByTestId("product-0");await first.locator("button.product-row-main").click();await first.locator("button.candidate-row").nth(1).click();await expect(page.getByTestId("estimated-total")).toHaveText("67,736원");await page.getByRole("button",{name:"5종 상세 확인하기"}).click();await expect(page.getByRole("button",{name:"5종 장바구니에 담기"})).toBeEnabled();await page.getByRole("button",{name:"5종 장바구니에 담기"}).click();await expect(page.getByRole("heading",{name:"정확하게 모두 담았어요"})).toBeVisible();await expect(page.getByLabel("담은 상품 가격 합계").getByText("67,736원",{exact:true})).toHaveCount(2);await page.locator("footer").getByRole("button",{name:"쿠팡 장바구니 보기"}).click();await expect(page.locator("html")).toHaveAttribute("data-demo-cart-opened","true");await page.locator("footer").getByRole("button",{name:"새 목록 담기"}).click();await expect(page.getByRole("heading",{name:"쇼핑 목록을 준비해 주세요"})).toBeVisible()});
test("system, light, and dark themes are available in the real side-panel component",async({page})=>{await page.goto("/dev/candidates?theme=dark");await expect(page.locator("html")).toHaveAttribute("data-theme","dark");await expect(page.getByTestId("theme-toggle")).toBeVisible();await expect(page.locator("main.app-shell")).toHaveScreenshot("candidates-dark.png",{animations:"disabled"});await page.getByTestId("theme-toggle").click();await expect(page.locator("html")).not.toHaveAttribute("data-theme");await page.getByTestId("theme-toggle").click();await expect(page.locator("html")).toHaveAttribute("data-theme","light")});

test("keeps existing candidates when the user appends another shopping line",async({page})=>{await page.goto("/dev/candidates");await page.getByRole("button",{name:"목록 더 추가"}).click();await page.getByLabel("추가할 쇼핑 목록").fill("제주삼다수 무라벨 2L 2개");await page.evaluate(()=>{chrome.runtime.sendMessage=(async(message:unknown)=>{const request=message as{type:string;items?:Array<{id:string}>};if(request.type!=="DDAKDAMA_SEARCH_ALL")return{ok:true};return{ok:true,output:(request.items??[]).map((line)=>({requestLineId:line.id,results:[{id:"added-water",productId:"9000",vendorItemId:"9001",itemId:null,title:"제주삼다수 무라벨 생수 2L 6개",currentPrice:7200,unitsPerPackage:6,productUrl:"https://www.coupang.com/vp/products/9000",imageUrl:null,rocketDelivery:true,rating:4.8,reviewCount:100,advertised:false,source:"BROWSER"}]}))}})as typeof chrome.runtime.sendMessage});await page.getByRole("button",{name:"목록에 추가하고 상품 찾기"}).click();await expect(page.getByText("제주삼다수 무라벨 생수 2L 6개",{exact:true})).toBeVisible();await expect(page.getByText("5/6종 선택",{exact:true})).toBeVisible();const added=page.getByTestId("product-5").locator("button.candidate-row");await expect(added).toHaveCount(1);await added.click();await expect(page.getByText("6/6종 선택",{exact:true})).toBeVisible()});

test("review has an explicit return to candidate selection",async({page})=>{await page.goto("/dev/preflight");await page.getByRole("button",{name:"후보·수량 다시 고르기"}).click();await expect(page.getByRole("heading",{name:"상품을 확인해 주세요"})).toBeVisible()});
