import{McpServer}from"@modelcontextprotocol/sdk/server/mcp.js";
import{registerAppResource,registerAppTool,RESOURCE_MIME_TYPE}from"@modelcontextprotocol/ext-apps/server";
import{z}from"zod";import{parseShoppingList,shoppingRequestLineSchema}from"@ddakdama/core";
import{completePairing,createHandoff,handoffStatus}from"./store.js";import{WIDGET_URI,widgetHtml}from"./widget.js";
const itemSchema=shoppingRequestLineSchema;
export function createMcpServer(){
 const server=new McpServer({name:"ddakdama",version:"1.0.0"},{instructions:"딱담아는 쇼핑 목록을 구조화하고 사용자가 검토한 계획을 페어링된 Chrome 확장 프로그램으로 보냅니다. 실제 상품 검색, 가격 검증과 장바구니 추가는 확장 프로그램에서 사용자 승인 후 진행합니다."});
 registerAppResource(server,"ddakdama-widget",WIDGET_URI,{},async()=>({contents:[{uri:WIDGET_URI,mimeType:RESOURCE_MIME_TYPE,text:widgetHtml,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},"openai/widgetDescription":"쇼핑 목록의 규격과 수량을 확인하고 딱담아 확장 프로그램으로 보내는 화면입니다.","openai/widgetPrefersBorder":true}}]}));
 registerAppTool(server,"parse_shopping_list",{title:"쇼핑 목록 분석",description:"사용자가 여러 줄의 쇼핑 목록을 제품명, 규격, 함량과 요청 수량으로 구조화하려 할 때 사용합니다.",inputSchema:{shopping_list:z.string().min(1).max(20000)},outputSchema:{items:z.array(itemSchema),itemKinds:z.number().int(),physicalUnits:z.number().int()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{ui:{resourceUri:WIDGET_URI},"openai/toolInvocation/invoking":"목록을 정확히 나누는 중…","openai/toolInvocation/invoked":"목록 확인 완료"}},async({shopping_list})=>{const items=parseShoppingList(shopping_list);const out={items,itemKinds:items.length,physicalUnits:items.reduce((s,x)=>s+x.requestedPhysicalUnits,0)};return{structuredContent:out,content:[{type:"text",text:`상품 ${out.itemKinds}종, 실물 ${out.physicalUnits}개로 인식했습니다.`}]}}); 
 registerAppTool(server,"create_cart_plan",{title:"장바구니 계획 만들기",description:"분석된 쇼핑 목록을 사용자가 위젯에서 검토할 장바구니 계획으로 표시할 때 사용합니다.",inputSchema:{shopping_list:z.string().min(1).max(20000)},outputSchema:{items:z.array(itemSchema),itemKinds:z.number().int(),physicalUnits:z.number().int()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{ui:{resourceUri:WIDGET_URI},"openai/toolInvocation/invoking":"장바구니 계획을 만드는 중…","openai/toolInvocation/invoked":"장바구니 계획 준비 완료"}},async({shopping_list})=>{const items=parseShoppingList(shopping_list);const out={items,itemKinds:items.length,physicalUnits:items.reduce((s,x)=>s+x.requestedPhysicalUnits,0)};return{structuredContent:out,content:[{type:"text",text:"딱담아 위젯에서 규격과 수량을 확인해 주세요."}]}}); 
 registerAppTool(server,"pair_extension_device",{title:"확장 프로그램 연결",description:"사용자가 확장 프로그램에 표시된 일회용 6자리 코드를 입력해 ChatGPT 앱과 연결할 때 사용합니다.",inputSchema:{pairing_code:z.string().regex(/^\d{6}$/)},outputSchema:{connected:z.boolean(),deviceId:z.string().optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true,idempotentHint:false},_meta:{ui:{resourceUri:WIDGET_URI}}},async({pairing_code})=>{const paired=completePairing(pairing_code);return paired?{structuredContent:{connected:true,deviceId:paired.deviceId},content:[{type:"text",text:"딱담아 확장 프로그램과 연결했습니다."}]}:{isError:true,structuredContent:{connected:false},content:[{type:"text",text:"페어링 코드가 만료되었거나 이미 사용되었습니다."}]}}); 
 registerAppTool(server,"send_cart_plan",{title:"딱담아로 보내기",description:"사용자가 확인한 장바구니 계획을 페어링된 확장 프로그램으로 전송할 때 사용합니다. 실제 장바구니 추가는 하지 않습니다.",inputSchema:{items:z.array(itemSchema).min(1),device_id:z.string().optional(),idempotency_key:z.string().min(8)},outputSchema:{sent:z.boolean(),handoffId:z.string().optional(),message:z.string()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true,idempotentHint:true},_meta:{ui:{resourceUri:WIDGET_URI},"openai/toolInvocation/invoking":"딱담아로 보내는 중…","openai/toolInvocation/invoked":"전송 완료"}},async({items,device_id,idempotency_key})=>{if(!device_id)return{isError:true,structuredContent:{sent:false,message:"확장 프로그램을 먼저 연결해 주세요."},content:[{type:"text",text:"확장 프로그램 연결이 필요합니다."}]};const h=createHandoff(device_id,{items},idempotency_key);return{structuredContent:{sent:true,handoffId:h.id,message:"확장 프로그램으로 보냈습니다."},content:[{type:"text",text:"딱담아 확장 프로그램에서 상품과 가격을 확인해 주세요."}]}}); 
 registerAppTool(server,"get_cart_plan_status",{title:"전송 상태 확인",description:"확장 프로그램이 장바구니 계획을 받았는지 확인할 때 사용합니다.",inputSchema:{handoff_id:z.string().uuid()},outputSchema:{found:z.boolean(),received:z.boolean().optional(),expired:z.boolean().optional()},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{}},async({handoff_id})=>{const s=handoffStatus(handoff_id);return{structuredContent:s?{found:true,...s}:{found:false},content:[{type:"text",text:s?(s.received?"확장 프로그램이 계획을 받았습니다.":"아직 확장 프로그램이 받지 않았습니다."):"전송 기록을 찾지 못했습니다."}]}}); 
 registerAppTool(server,"get_service_status",{title:"딱담아 상태 확인",description:"딱담아 서비스가 현재 사용 가능한지 확인할 때 사용합니다.",inputSchema:{},outputSchema:{status:z.enum(["available","degraded","unavailable"])},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{}},async()=>({structuredContent:{status:"available"},content:[{type:"text",text:"딱담아를 사용할 수 있습니다."}]}));
 return server;
}
