import{createHmac}from"node:crypto";
const base="https://api-gateway.coupang.com";
const root="/v2/providers/affiliate_open_api/apis/openapi/v1";
export type PartnersConfig={accessKey:string;secretKey:string;subId:string};
export const partnersConfig=():PartnersConfig=>({accessKey:String(process.env.COUPANG_PARTNERS_ACCESS_KEY??"").trim(),secretKey:String(process.env.COUPANG_PARTNERS_SECRET_KEY??"").trim(),subId:String(process.env.COUPANG_PARTNERS_SUB_ID??"ddakdama-extension").replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,64)});
export const partnersConfigured=(config=partnersConfig())=>Boolean(config.accessKey&&config.secretKey);
export function signedDate(date=new Date()){const p=(n:number)=>String(n).padStart(2,"0");return String(date.getUTCFullYear()).slice(-2)+p(date.getUTCMonth()+1)+p(date.getUTCDate())+"T"+p(date.getUTCHours())+p(date.getUTCMinutes())+p(date.getUTCSeconds())+"Z"}
export function authorization(method:string,pathWithQuery:string,config:PartnersConfig,date=new Date()){if(!partnersConfigured(config))throw new Error("PARTNERS_NOT_CONFIGURED");const[path,query=""]=pathWithQuery.split("?");const stamp=signedDate(date);const signature=createHmac("sha256",config.secretKey).update(stamp+method.toUpperCase()+path+query).digest("hex");return`CEA algorithm=HmacSHA256, access-key=${config.accessKey}, signed-date=${stamp}, signature=${signature}`}
async function call(pathWithQuery:string,init:RequestInit,config=partnersConfig()){const response=await fetch(base+pathWithQuery,{...init,headers:{accept:"application/json","content-type":"application/json; charset=utf-8",authorization:authorization(init.method??"GET",pathWithQuery,config),"user-agent":"ddakdama/1.0.0",...(init.headers??{})},signal:AbortSignal.timeout(8000)});const payload=await response.json().catch(()=>({}));if(!response.ok||String(payload?.rCode??"0")!=="0")throw new Error(payload?.rMessage??payload?.message??`PARTNERS_HTTP_${response.status}`);return payload}
export async function searchProducts(keyword:string,limit=10,config=partnersConfig()){const query=new URLSearchParams({keyword,limit:String(Math.max(1,Math.min(10,limit))),subId:config.subId});return call(`${root}/products/search?${query}`,{method:"GET"},config)}
export async function createDeepLinks(urls:string[],config=partnersConfig()){const coupangUrls=[...new Set(urls)].filter(value=>{try{const url=new URL(value);return url.protocol==="https:"&&/(^|\.)coupang\.com$/i.test(url.hostname)}catch{return false}}).slice(0,20);if(!coupangUrls.length)throw new Error("NO_VALID_COUPANG_URL");return call(`${root}/deeplink`,{method:"POST",body:JSON.stringify({coupangUrls,subId:config.subId})},config)}
