export const WIDGET_URI="ui://widget/ddakdama-cart-v1.html";
export const widgetHtml=`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<style>
:root{font-family:Inter,Pretendard,system-ui,sans-serif;color:#17191c}*{box-sizing:border-box}body{margin:0;padding:16px;background:#fff}.wrap{border:1px solid #e7eaf0;border-radius:20px;padding:18px;box-shadow:0 10px 30px #172b4d0d}h2{margin:0;font-size:20px}.sub{color:#747b87;font-size:13px;margin:6px 0 16px}.summary{display:flex;justify-content:space-between;background:#f5f8ff;padding:12px;border-radius:12px;font-weight:700}.items{margin:14px 0;display:grid;gap:8px}.item{padding:10px 0;border-bottom:1px solid #eef0f3}.item b{font-size:13px}.item small{display:block;color:#747b87;margin-top:4px}.pair{display:flex;gap:8px;margin:12px 0}.pair input{min-width:0;flex:1;border:1px solid #dfe3e9;border-radius:12px;padding:11px;font-size:16px;letter-spacing:4px;text-align:center}.pair button{border:0;border-radius:12px;padding:0 14px;font-weight:750;color:#1769ff;background:#edf4ff}.action{width:100%;border:0;border-radius:13px;background:#1769ff;color:white;padding:13px;font-weight:800}.action:disabled{background:#d9dde4;color:#8a929d}.status{text-align:center;color:#657080;font-size:11px;margin-top:9px}</style></head>
<body><main class="wrap"><h2>딱담아</h2><p class="sub">쇼핑 목록을 정확한 규격과 수량으로 확인했어요.</p><div class="summary"><span id="kinds">상품 0종</span><span id="units">실물 0개</span></div><div class="items" id="items"></div><div class="pair"><input id="pairing" inputmode="numeric" maxlength="6" placeholder="확장 프로그램의 6자리 코드" aria-label="페어링 코드"><button id="pair">연결</button></div><button class="action" id="send" disabled>딱담아 확장 프로그램으로 보내기</button><p class="status" id="status">먼저 확장 프로그램에 표시된 코드를 연결해 주세요.</p></main>
<script type="module">
let plan=window.openai?.toolOutput||{};let deviceId=null;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const render=()=>{const items=plan.items||[];document.querySelector("#kinds").textContent="상품 "+items.length+"종";document.querySelector("#units").textContent="실물 "+items.reduce((s,x)=>s+x.requestedPhysicalUnits,0)+"개";document.querySelector("#items").innerHTML=items.map(x=>'<div class="item"><b>'+esc(x.productName)+'</b><small>'+esc([x.unitSizeValue&&x.unitSizeValue+(x.unitSizeUnit||""),x.strengthValue&&x.strengthValue+(x.strengthUnit||""),x.packageContentCount&&x.packageContentCount+(x.packageContentUnit||""),"수량 "+x.requestedPhysicalUnits].filter(Boolean).join(" · "))+'</small></div>').join("")};
window.addEventListener("message",event=>{if(event.data?.method==="ui/notifications/tool-result"&&event.data.params?.structuredContent?.items){plan=event.data.params.structuredContent;render()}});
document.querySelector("#pair").onclick=async()=>{const code=document.querySelector("#pairing").value.trim();if(!/^\d{6}$/.test(code)){document.querySelector("#status").textContent="6자리 코드를 입력해 주세요.";return}document.querySelector("#status").textContent="연결 중…";try{const response=await window.openai.callTool("pair_extension_device",{pairing_code:code});deviceId=response?.structuredContent?.deviceId||null;document.querySelector("#send").disabled=!deviceId;document.querySelector("#status").textContent=deviceId?"확장 프로그램과 연결됐습니다.":"코드가 만료되었습니다."}catch{document.querySelector("#status").textContent="연결하지 못했습니다. 새 코드를 확인해 주세요."}};
document.querySelector("#send").onclick=async()=>{if(!deviceId)return;document.querySelector("#status").textContent="확장 프로그램으로 전송 중…";try{const response=await window.openai.callTool("send_cart_plan",{items:plan.items,device_id:deviceId,idempotency_key:crypto.randomUUID()});document.querySelector("#status").textContent=response?.structuredContent?.message||"전송했습니다."}catch{document.querySelector("#status").textContent="전송하지 못했습니다. 연결을 확인해 주세요."}};
render();
</script></body></html>`;
