chrome.runtime.onInstalled.addListener(()=>chrome.sidePanel.setPanelBehavior({openPanelOnActionClick:true}));
type Job={id:string;productUrl:string;productId:string;cartPurchaseQuantity:number;status:string};
const journalKey="ddakdama-cart-journal";
async function sendToTab(tabId:number,message:unknown){return chrome.tabs.sendMessage(tabId,message)}
async function cartSnapshot(){const tab=await chrome.tabs.create({url:"https://cart.coupang.com/cartView.pang",active:false});if(!tab.id)throw new Error("CART_TAB_FAILED");try{await waitComplete(tab.id);return await sendToTab(tab.id,{type:"DDAKDAMA_CART_SNAPSHOT"})}finally{await chrome.tabs.remove(tab.id).catch(()=>{})}}
async function waitComplete(tabId:number){const current=await chrome.tabs.get(tabId);if(current.status==="complete")return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>done(new Error("NETWORK_ERROR")),15000);const listener=(id:number,info:{status?:string})=>{if(id===tabId&&info.status==="complete")done()};const done=(error?:Error)=>{clearTimeout(timer);chrome.tabs.onUpdated.removeListener(listener);if(error)reject(error);else resolve()};chrome.tabs.onUpdated.addListener(listener)})}
async function runJob(job:Job){const before=await cartSnapshot();const existing=before.items?.find((x:{productId:string})=>x.productId===job.productId)?.quantity??0;const tab=await chrome.tabs.create({url:job.productUrl,active:false});if(!tab.id)throw new Error("PRODUCT_TAB_FAILED");try{await waitComplete(tab.id);const detail=await sendToTab(tab.id,{type:"DDAKDAMA_INSPECT_PRODUCT"});if(detail.productId!==job.productId)return{...job,status:"PRODUCT_MISMATCH"};if(!detail.price)return{...job,status:"PRICE_UNVERIFIED"};if(detail.optionRequired)return{...job,status:"OPTION_REQUIRED"};if(!detail.inStock)return{...job,status:"OUT_OF_STOCK"};for(let i=0;i<job.cartPurchaseQuantity;i++){const added=await sendToTab(tab.id,{type:"DDAKDAMA_ADD_TO_CART"});if(!added.ok)return{...job,status:added.reason??"ADD_BUTTON_NOT_FOUND"}}const after=await cartSnapshot();const next=after.items?.find((x:{productId:string})=>x.productId===job.productId)?.quantity??0;return{...job,status:next-existing===job.cartPurchaseQuantity?"SUCCESS":"QUANTITY_MISMATCH",beforeQuantity:existing,afterQuantity:next,verifiedPrice:detail.price}}finally{await chrome.tabs.remove(tab.id).catch(()=>{})}}
async function searchOne(query:string){const tab=await chrome.tabs.create({url:"https://www.coupang.com/np/search?q="+encodeURIComponent(query),active:false});if(!tab.id)throw new Error("SEARCH_TAB_FAILED");try{await waitComplete(tab.id);const value=await sendToTab(tab.id,{type:"DDAKDAMA_SEARCH_RESULTS"});return value?.results??[]}finally{await chrome.tabs.remove(tab.id).catch(()=>{})}}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{
 if(message?.type==="DDAKDAMA_OPEN_CART"){chrome.tabs.create({url:"https://cart.coupang.com/cartView.pang"});sendResponse({ok:true});return false}
 if(message?.type==="DDAKDAMA_RUN_CART_JOBS"){(async()=>{const jobs:Job[]=message.jobs??[];await chrome.storage.local.set({[journalKey]:{jobs,startedAt:Date.now()}});const results=[];for(const job of jobs){results.push(await runJob(job).catch(error=>({...job,status:error?.message??"UNKNOWN_ERROR"})));await chrome.storage.local.set({[journalKey]:{jobs,results,updatedAt:Date.now()}})}sendResponse({ok:true,results})})();return true}
 if(message?.type==="DDAKDAMA_SEARCH_ALL"){(async()=>{const output=[];for(const item of message.items??[]){try{output.push({requestLineId:item.id,results:await searchOne(item.rawText)})}catch(error){output.push({requestLineId:item.id,results:[],error:error instanceof Error?error.message:"SEARCH_FAILED"})}}sendResponse({ok:true,output})})();return true}
 return false;
});
